#!/bin/bash

# ICT171 Server Status Script
# This script creates a simple HTML status page for the International Student Hub server.

OUTPUT="/var/www/html/server-status.html"

NOW=$(date)
HOSTNAME=$(hostname)
UPTIME=$(uptime -p)
DISK_USAGE=$(df -h / | awk 'NR==2 {print $5 " used of " $2}')
MEMORY_USAGE=$(free -h | awk '/Mem:/ {print $3 " used of " $2}')
NGINX_STATUS=$(systemctl is-active nginx)
PUBLIC_IP="40.81.23.165"
DOMAIN="internationalstudenthub.site"

cat > "$OUTPUT" <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>Server Status - International Student Hub</title>
</head>
<body>
    <h1>International Student Hub - Server Status</h1>

    <p><strong>Generated on:</strong> $NOW</p>
    <p><strong>Hostname:</strong> $HOSTNAME</p>
    <p><strong>Domain:</strong> $DOMAIN</p>
    <p><strong>Public IP:</strong> $PUBLIC_IP</p>
    <p><strong>Server uptime:</strong> $UPTIME</p>
    <p><strong>Disk usage:</strong> $DISK_USAGE</p>
    <p><strong>Memory usage:</strong> $MEMORY_USAGE</p>
    <p><strong>NGINX status:</strong> $NGINX_STATUS</p>

    <h2>Script Purpose</h2>
    <p>This page was generated by a Bash script. The script checks useful server information and displays it as a web page so the output can be verified online.</p>
</body>
</html>
EOF

echo "Server status page created at $OUTPUT"
